

/**
 * Contains foxed words for Uniformity test.
 */
public class FixedWordDic {
  String[] words = {"Wora", "Worb", "Worc", "Word", "Wore", "Worf", "Worg", "Worh", "Wori", "Worj",
"Work", "Worl", "Worm", "Worn", "Woro", "Worp", "Worq", "Worr", "Wors", "Wort", "Woru", "Worv", "Worw",
"Worx", "Wory", "Worz", "wora", "worb", "worc", "word", "wore", "worf", "worg", "worh", "wori", "worj",
"work", "worl", "worm", "worn", "woro", "worp", "worq", "worr", "wors", "wort", "woru", "worv", "worw",
"worx", "wory", "worz", "wOra", "wOrb", "wOrc", "wOrd", "wOre", "wOrf", "wOrg", "wOrh", "wOri", "wOrj",
"wOrk", "wOrl", "wOrm", "wOrn", "wOro", "wOrp", "wOrq", "wOrr", "wOrs", "wOrt", "wOru", "wOrv", "wOrw",
"wOrx", "wOry", "wOrz", "Aord", "Bord", "Cord", "Dord", "Eord", "Ford", "Gord", "Hord", "Iord", "Jord",
"Kord", "Lord", "Mord", "Nord", "Oord", "Pord", "Qord", "Rord", "Sord", "Tord", "Uord", "Vord", "Wodr",
"Xord", "Yord", "Zord", "Ward", "Wbrd", "Wcrd", "Wdrd", "Werd", "Wfrd", "Wgrd", "Whrd", "Wird", "Wjrd",
"Wkrd", "Wlrd", "Wmrd", "Wnrd", "Wprd", "Wqrd", "Wrrd", "Wsrd", "Wtrd", "Wurd", "Wvrd", "Wwdr",
"Wxrd", "Wyrd", "Wzrd", "Woad", "Wobd", "Wocd", "Wodd", "Woed", "Wofd", "Wogd", "Wohd", "Woid", "Wojd",
"Wokd", "Wold", "Womd", "Wond", "Wopd", "Woqd", "Wosd", "Wotd", "Woud", "Wovd", "Wowr",
"Woxd", "Woyd", "Wozd", "Wora", "Worb", "Worc", "Wore", "Worf", "Worg", "Worh", "Wori", "Worj",
"Work", "Worl", "Worm", "Worn", "Worp", "Worq", "Wors", "Wort", "Woru", "Worv", "Worw",
"Worx", "Wory", "Worz", "Aog", "Bog", "Cog", "Dog", "Eog", "Fog", "Gog", "Hog", "Iog", "Jog", "Kog", "Log", "Mog",
"Nog", "Oog", "Pog", "Qog", "Rog", "Sog", "Tog", "Uog", "Vog", "Wog", "Xog", "Yog", "Zog", "Dag", "Dbg", "Dcg", "Ddg",
"Deg", "Dfg", "Dgg", "Dhg", "Dig", "Djg", "Dkg", "Dlg", "Dmg", "Dng", "Dpg", "Dqg", "Drg", "Dsg", "Dtg", "Dug", "Dvg",
"Dwg", "Dxg", "Dyg", "Dzg", "Doa", "Dob", "Doc", "Dod", "Doe", "Dof", "Doh", "Doi", "Doj", "Dok", "Dol", "Dom", "Don", 
"Doo", "Dop", "Doq", "Dor", "Dos", "Dot", "Dou", "Dov", "Dow", "Dox", "Doy", "Doz", "AOg", "BOg", "COg", "DOg", "EOg",
 "FOg", "GOg", "HOg", "IOg", "JOg", "KOg", "LOg", "MOg", "NOg", "OOg", "POg", "QOg", "ROg", "SOg", "TOg", "UOg", "VOg",
  "WOg", "XOg", "YOg", "ZOg", "Aund", "Bund", "Cund", "Dund", "Eund", "Fund", "Gund", "Hund", "Iund", "Jund", "Kund", "Mund",
"Nund", "Ound", "Pund", "Qund", "Rund", "Sund", "Tund", "Uund", "Vund", "Wund", "Xund", "Yund", "Zund", "Hand", "Hbnd", "Hcnd",
"Hdnd", "Hend", "Hfnd", "Hgnd", "Hhnd", "Hind", "Hjnd", "Hknd", "Hlnd", "Hmnd", "Hnnd", "Hond", "Hpnd", "Hqnd", "Hrnd", "Hsnt",
"Htnd", "Hvnd", "Hwnd", "Hxnd", "Hynd", "Hznd", "Huan", "Hubn", "Hucn", "Hudn", "Huend", "Huefn", "Hugn", "Huhn", "Huin", "Hujn",
"Hukn", "Humn", "Hunn", "Huon", "Hupn", "Huqn", "Hurn", "Husn", "Hutn", "Huun", "Huvn", "Huwn", "Huxn", "Huyn", "Huzn", "Huna",
"Hunb", "Hunc", "Hune", "Hunf", "Hung", "Hunh", "Huni", "Hunj", "Hunk", "Hunl", "Hunm", "Huno", "Hunp", "Hunq", "Hunr", "Huns", "Hunp",
"Hunq", "Hunr", "Huns", "Hunt", "Hunu", "Hunv", "Hunw", "Hunx", "Huny", "Hunz", "Aatt", "Batt", "Catt", "Datt", "Eatt", "Fatt", "Gatt",
"Hatt", "Iatt", "Jatt", "Katt", "Latt", "Matt", "Natt", "Oatt", "Patt", "Qatt", "Ratt", "Satt", "Tatt", "Uatt", "Vatt", "Watt", "Xatt",
"Yatt", "Zatt", "Kbtt", "Kctt", "Kdtt", "Kett", "Kftt", "Kgtt", "Khtt", "Kitt", "Kjtt", "Kktt", "Kmtt", "Kntt", "Kott", "Kptt", "Kqtt",
"Krtt", "Kstt", "Kttt", "Kutt", "Kvtt", "KKwtt", "Kxtt", "Kytt", "Kztt", "Kaat", "Kabt", "Kact", "Kadt", "Kaet", "Kaft", "Kagt", "Kaht",
"Kait", "Kajt", "Kakt", "Kalt", "Kamt", "Kant", "Kaot", "Kapt", "Kaqt", "Kart", "Kast", "Kaut", "Kavt", "Kawt", "Kaxt", "Kayt", "Kazt",
"Kata", "Katb", "Katc", "Katd", "Kate", "Katf", "Katg", "Kath", "Kati", "Katj", "Katk", "Katl", "Katm", "Katn", "Kato", "Katp", "Katq",
"Katr", "Kats", "Katu", "Katv", "Katw", "Katx", "Katy", "Katz", "Aaffe", "Baffe", "Caffe", "Daffe", "Eaffe", "Faffe", "Gaffe", "Haffe",
"Iaffe", "Jaffe", "Kaffe", "Laffe", "Maffe", "Naffe", "Oaffe", "Paffe", "Qaffe", "Raffe", "Saffe", "Taffe", "Uaffe", "Vaffe", "Waffe",
"Xaffe", "Yaffe", "Zaffe", "Kbffe", "Kcffe", "Kdffe", "Keffe", "Kfffe", "Kgffe", "Khhffe", "Kiffe", "Kjffe", "Kkffe", "Klffe", "Kmffe",
"Knffe", "Koffe", "Kpffe", "Kqffe", "Krffe", "Ksffe", "Ktffe", "Kuffe", "Kvffe", "Kwffe", "Kxffe", "Kyffe", "Kzffe", "Kaafe", "Kacfe", "Kabfe",
"Kadfe", "Kaefe", "Kagfe", "Kahfe", "Kaife", "Kajfe", "Kakfe", "Kalfe", "Kamfe", "Kanfe", "Kaofe", "Karfe", "Kasfe", "Katfe", "Kaufe",
"Kavfe", "Kawfe", "Kaxfe", "Kayfe", "Kaze", "Kafae", "Kafbe", "Kafce", "Kafde", "Kafee", "Kafge", "Kafhe", "Kafie", "Kafje", "Kafke",
"Kafle", "Kafme", "Kafne", "Kafoe", "Kafpe", "Kafqe", "Kafre", "Kafse", "Kafte", "Kafue", "Kafve", "Kafwe", "Kafxe", "Kafye", "Kafze",
"Kaffa", "Kaffc", "Kaffd", "Kafff", "Kaffg", "Kaffh", "Kaffi", "Kaffj", "Kaffk", "Kaffl", "Kaffm", "Kaffn", "Kaffo", "Kaffp", "Kaffq",
"Kaffr", "Kaffs", "Kafft", "Kaffu", "Kaffv", "Kaffw", "Kaffx", "Kaffy", "Kaffz", "aog", "bog", "cog", "dog", "eog", "fog", "gog",
 "hog", "iog", "jog", "kog", "log", "mog", "nog", "oog", "pog", "qog", "rog", "sog", "tog", "uog", "vog", "wog", "xog",
  "yog", "dog", "dag", "dbg", "dcg", "ddg","deg", "dfg", "dgg", "dhg", "dig", "djg", "dkg", "dlg", "dmg", "dng",
   "dpg", "dqg", "drg", "dsg", "dtg", "dug", "dvg",
"dwg", "dxg", "dyg", "dzg", "doa", "dob", "doc", "dod", "doe", "dof", "doh", "doi", "doj", "dok", "dol", "dom", "don", 
"eoo", "eop", "eoq", "eor", "eos", "eot", "eou", "eov", "eow", "eox", "eoy", "eoz", "eOg", "eOg", "eOg", "eOg", "eOg",
 "fOg", "gOg", "hOg", "iOg", "jOg", "kOg", "lOg", "mOg", "nOg", "oOg", "pOg", "qOg", "rOg", "sOg", "tOg", "uOg", "vOg",
  "wOg", "xOg", "yOg", "zOg", "aund", "bund", "cund", "dund", "eund", "fund", "gund", "hund", "iund", "jund", "kund", "mund",
"nund", "ound", "pund", "qund", "rund", "sund", "tund", "uund", "vund", "wund", "xund", "yund", "zund", "hand", "hbnd", "hcnd",
"hdnd", "hend", "hfnd", "hgnd", "hhnd", "hind", "hjnd", "hknd", "hlnd", "hmnd", "hnnd", "hond", "hpnd", "hqnd", "hrnd", "hsnt",
"htnd", "hvnd", "hwnd", "hxnd", "hynd", "hznd", "huan", "hubn", "hucn", "hudn", "huend", "huefn", "hugn", "huhn", "huin", "hujn",
"hukn", "humn", "hunn", "huon", "hupn", "huqn", "hurn", "husn", "hutn", "huun", "huvn", "huwn", "huxn", "huyn", "huzn", "huna",
"hunb", "hunc", "hune", "hunf", "hung", "hunh", "huni", "hunj", "hunk", "hunl", "hunm", "huno", "hunp", "hunq", "hunr", "huns", "hunp",
"hunq", "hunr", "huns", "hunt", "hunu", "hunv", "hunw", "hunx", "huny", "hunz", "aatt", "batt", "catt", "datt", "eatt", "fatt", "gatt",
"hatt", "iatt", "jatt", "katt", "latt", "matt", "natt", "oatt", "patt", "qatt", "ratt", "satt", "tatt", "uatt", "vatt", "watt", "xatt",
"yatt", "zatt", "kbtt", "kctt", "kdtt", "kett", "kftt", "kgtt", "khtt", "kitt", "kjtt", "kktt", "kmtt", "kntt", "kott", "kptt", "kqtt",
"krtt", "kstt", "kttt", "kutt", "kvtt", "kwtt", "kxtt", "kytt", "kztt", "kaat", "kabt", "kact", "kadt", "kaet", "kaft", "kagt", "kaht",
"kait", "kajt", "kakt", "kalt", "kamt", "kant", "kaot", "kapt", "kaqt", "kart", "kast", "kaut", "kavt", "kawt", "kaxt", "kayt", "kazt",
"kata", "katb", "katc", "katd", "kate", "katf", "katg", "kath", "kati", "katj", "katk", "katl", "katm", "katn", "kato", "katp", "katq",
"katr", "kats", "katu", "katv", "katw", "katx", "katy", "katz", "aaffe", "baffe", "caffe", "daffe", "eaffe", "faffe", "gaffe", "haffe",
"iaffe", "jaffe", "kaffe", "laffe", "maffe", "naffe", "oaffe", "paffe", "qaffe", "raffe", "saffe", "taffe", "uaffe", "vaffe", "waffe",
"xaffe", "yaffe", "kaffe", "kbffe", "kcffe", "kdffe", "keffe", "kfffe", "kgffe", "khhffe", "kiffe", "kjffe", "kkffe", "klffe", "kmffe",
"knffe", "koffe", "kpffe", "kqffe", "krffe", "ksffe", "ktffe", "kuffe", "kvffe", "kwffe", "kxffe", "kyffe", "kzffe", "kaafe", "kacfe", "kabfe",
"kadfe", "kaefe", "kagfe", "kahfe", "kaife", "kajfe", "kakfe", "kalfe", "kamfe", "kanfe", "kaofe", "karfe", "kasfe", "katfe", "kaufe",
"kavfe", "kawfe", "kaxfe", "kayfe", "kaze", "kafae", "kafbe", "kafce", "kafde", "kafee", "kafge", "kafhe", "kafie", "kafje", "kafke",
"kafle", "kafme", "kafne", "kafoe", "kafpe", "kafqe", "kafre", "kafse", "kafte", "kafue", "kafve", "kafwe", "kafxe", "kafye", "kafze",
"kaffa", "kaffc", "kaffd", "kafff", "kaffg", "kaffh", "kaffi", "kaffj", "kaffk", "kaffl", "kaffm", "kaffn", "kaffo", "kaffp", "kaffq",
"kaffr", "kaffs", "kafft", "kaffu", "kaffv", "kaffw", "kaffx", "kaffy", "kaffz"};


  String[] getWords() {
    return words;
  }
}
